name: Latex Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-latex:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Set up LaTeX environment
      uses: evanp/latex-action@v2.1.0
      with:
        version: "texlive" # or "texlive" for TeX Live or "miktex" for MiKTeX
    - name: Build LaTeX Document(s)
      uses: rstacruz/latex-compile@v1.1.0
      with:
        source_file: "*.tex" # replace "your_latex_file.tex" with the name of your LaTeX file(s) separated by commas for multiple files. You can also use wildcards like "*" or "**" to compile all LaTeX files in a directory or subdirectory. ```
